// <auto-generated />
using System;
using Bdapis.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bdapis.Server.Migrations
{
    [DbContext(typeof(BDPatrocinadorContext))]
    [Migration("20230518155626_nuevastab")]
    partial class nuevastab
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bdapis.Shared.Modelo.Anuncios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Costo")
                        .HasColumnType("int");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Anuncios");
                });

            modelBuilder.Entity("Bdapis.Shared.Modelo.Ingresos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnuncioId")
                        .HasColumnType("int");

                    b.Property<int?>("AnunciosId")
                        .HasColumnType("int");

                    b.Property<int>("Pagado")
                        .HasColumnType("int");

                    b.Property<int>("PatrocinadorId")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnunciosId");

                    b.HasIndex("PatrocinadorId");

                    b.ToTable("Ingresos");
                });

            modelBuilder.Entity("Bdapis.Shared.Modelo.Patrocinador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Patrocinadores");
                });

            modelBuilder.Entity("Bdapis.Shared.Modelo.Transmisiones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnunciosId")
                        .HasColumnType("int");

                    b.Property<string>("Encuentro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Torneo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnunciosId");

                    b.ToTable("Transmisiones");
                });

            modelBuilder.Entity("Bdapis.Shared.Modelo.Ingresos", b =>
                {
                    b.HasOne("Bdapis.Shared.Modelo.Anuncios", "Anuncios")
                        .WithMany()
                        .HasForeignKey("AnunciosId");

                    b.HasOne("Bdapis.Shared.Modelo.Patrocinador", "Patrocinador")
                        .WithMany("Ingresos")
                        .HasForeignKey("PatrocinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anuncios");

                    b.Navigation("Patrocinador");
                });

            modelBuilder.Entity("Bdapis.Shared.Modelo.Transmisiones", b =>
                {
                    b.HasOne("Bdapis.Shared.Modelo.Anuncios", null)
                        .WithMany("Transmisiones")
                        .HasForeignKey("AnunciosId");
                });

            modelBuilder.Entity("Bdapis.Shared.Modelo.Anuncios", b =>
                {
                    b.Navigation("Transmisiones");
                });

            modelBuilder.Entity("Bdapis.Shared.Modelo.Patrocinador", b =>
                {
                    b.Navigation("Ingresos");
                });
#pragma warning restore 612, 618
        }
    }
}
